package com.sbb.mymanager;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.sbb.mymanager.Cattle;
import com.sbb.mymanager.BullOrigin;
import com.sbb.mymanager.Vaccine;
import com.sbb.mymanager.VaccineControl;
import com.sbb.mymanager.PalpationControl;
import com.sbb.mymanager.InseminationControl;
import com.sbb.mymanager.TaggingControl;

import com.sbb.mymanager.CattleDao;
import com.sbb.mymanager.BullOriginDao;
import com.sbb.mymanager.VaccineDao;
import com.sbb.mymanager.VaccineControlDao;
import com.sbb.mymanager.PalpationControlDao;
import com.sbb.mymanager.InseminationControlDao;
import com.sbb.mymanager.TaggingControlDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cattleDaoConfig;
    private final DaoConfig bullOriginDaoConfig;
    private final DaoConfig vaccineDaoConfig;
    private final DaoConfig vaccineControlDaoConfig;
    private final DaoConfig palpationControlDaoConfig;
    private final DaoConfig inseminationControlDaoConfig;
    private final DaoConfig taggingControlDaoConfig;

    private final CattleDao cattleDao;
    private final BullOriginDao bullOriginDao;
    private final VaccineDao vaccineDao;
    private final VaccineControlDao vaccineControlDao;
    private final PalpationControlDao palpationControlDao;
    private final InseminationControlDao inseminationControlDao;
    private final TaggingControlDao taggingControlDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cattleDaoConfig = daoConfigMap.get(CattleDao.class).clone();
        cattleDaoConfig.initIdentityScope(type);

        bullOriginDaoConfig = daoConfigMap.get(BullOriginDao.class).clone();
        bullOriginDaoConfig.initIdentityScope(type);

        vaccineDaoConfig = daoConfigMap.get(VaccineDao.class).clone();
        vaccineDaoConfig.initIdentityScope(type);

        vaccineControlDaoConfig = daoConfigMap.get(VaccineControlDao.class).clone();
        vaccineControlDaoConfig.initIdentityScope(type);

        palpationControlDaoConfig = daoConfigMap.get(PalpationControlDao.class).clone();
        palpationControlDaoConfig.initIdentityScope(type);

        inseminationControlDaoConfig = daoConfigMap.get(InseminationControlDao.class).clone();
        inseminationControlDaoConfig.initIdentityScope(type);

        taggingControlDaoConfig = daoConfigMap.get(TaggingControlDao.class).clone();
        taggingControlDaoConfig.initIdentityScope(type);

        cattleDao = new CattleDao(cattleDaoConfig, this);
        bullOriginDao = new BullOriginDao(bullOriginDaoConfig, this);
        vaccineDao = new VaccineDao(vaccineDaoConfig, this);
        vaccineControlDao = new VaccineControlDao(vaccineControlDaoConfig, this);
        palpationControlDao = new PalpationControlDao(palpationControlDaoConfig, this);
        inseminationControlDao = new InseminationControlDao(inseminationControlDaoConfig, this);
        taggingControlDao = new TaggingControlDao(taggingControlDaoConfig, this);

        registerDao(Cattle.class, cattleDao);
        registerDao(BullOrigin.class, bullOriginDao);
        registerDao(Vaccine.class, vaccineDao);
        registerDao(VaccineControl.class, vaccineControlDao);
        registerDao(PalpationControl.class, palpationControlDao);
        registerDao(InseminationControl.class, inseminationControlDao);
        registerDao(TaggingControl.class, taggingControlDao);
    }
    
    public void clear() {
        cattleDaoConfig.getIdentityScope().clear();
        bullOriginDaoConfig.getIdentityScope().clear();
        vaccineDaoConfig.getIdentityScope().clear();
        vaccineControlDaoConfig.getIdentityScope().clear();
        palpationControlDaoConfig.getIdentityScope().clear();
        inseminationControlDaoConfig.getIdentityScope().clear();
        taggingControlDaoConfig.getIdentityScope().clear();
    }

    public CattleDao getCattleDao() {
        return cattleDao;
    }

    public BullOriginDao getBullOriginDao() {
        return bullOriginDao;
    }

    public VaccineDao getVaccineDao() {
        return vaccineDao;
    }

    public VaccineControlDao getVaccineControlDao() {
        return vaccineControlDao;
    }

    public PalpationControlDao getPalpationControlDao() {
        return palpationControlDao;
    }

    public InseminationControlDao getInseminationControlDao() {
        return inseminationControlDao;
    }

    public TaggingControlDao getTaggingControlDao() {
        return taggingControlDao;
    }

}
